### ISSUE TITLE
[SUGGESTION] Hide Toolbar?

### ISSUE THREAD

**Issue by schmidhauser** [ijgnd/anki__browser_MaximizeHide_TableEditor#5]
I was wondering if there was a possibility that you add a further option to hide the toolbar between the Card List and the Editor. It takes up so much space. I also never click on the icons since I know the shortcuts by heart.

<img width="954" alt="toolbar" src="https://user-images.githubusercontent.com/519178/138810859-700046a3-72f8-4ab1-9688-a5cbdeb6d4b1.png">

**Comment by ijgnd** [comment]
I like this idea.

But at the moment I doubt that it's a good fit into my add-on. I think it would make more sense to have it as a standalone add-on because if you know your shortcuts you never need the ~~shortcuts~~ [edit: icons] - not in the default browser mode and not in the editor?

There's also a practical problem - my add-on modifies only a few pyqt options whereas the toolbar buttons are drawn with in the editor webview. henrik rewrote this part of the code for .45+. I have never looked at this code. I'd repost this question in the anki forum and ping hengiesel - this could be a quick fix for him so that he might be interested in making it.

**Comment by ijgnd** [comment]
I opened a topic about this at https://forums.ankiweb.net/t/hide-buttons-in-the-editor/14711/4
